// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE0R0U97mZ6OQowygw3nWFfyuzPZGYnrA',
    appId: '1:794741775127:web:260aa57a8f92a8bab53552',
    messagingSenderId: '794741775127',
    projectId: 'projeto-4d2f7',
    authDomain: 'projeto-4d2f7.firebaseapp.com',
    storageBucket: 'projeto-4d2f7.firebasestorage.app',
    measurementId: 'G-8ZNBCLBPF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwdvrXo66_b_uy37jtaei5HwaZkgw18Lk',
    appId: '1:794741775127:android:26f202f6f1fb62c6b53552',
    messagingSenderId: '794741775127',
    projectId: 'projeto-4d2f7',
    storageBucket: 'projeto-4d2f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZMV974HE_zQOVROR2KanXIhuNu-28GG4',
    appId: '1:794741775127:ios:f618e68a9a5c25f3b53552',
    messagingSenderId: '794741775127',
    projectId: 'projeto-4d2f7',
    storageBucket: 'projeto-4d2f7.firebasestorage.app',
    iosBundleId: 'com.example.projeto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZMV974HE_zQOVROR2KanXIhuNu-28GG4',
    appId: '1:794741775127:ios:f618e68a9a5c25f3b53552',
    messagingSenderId: '794741775127',
    projectId: 'projeto-4d2f7',
    storageBucket: 'projeto-4d2f7.firebasestorage.app',
    iosBundleId: 'com.example.projeto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE0R0U97mZ6OQowygw3nWFfyuzPZGYnrA',
    appId: '1:794741775127:web:9715b93e26645ecab53552',
    messagingSenderId: '794741775127',
    projectId: 'projeto-4d2f7',
    authDomain: 'projeto-4d2f7.firebaseapp.com',
    storageBucket: 'projeto-4d2f7.firebasestorage.app',
    measurementId: 'G-7N8Z8L61M3',
  );
}
